[package]
name = "rlox"
version = "0.1.0"
edition = "2021"
authors = ["Gabriel Bento <gabrielorigenstdb@gmail.com>"]
description = "A Tree-Walk interpreter for Lox language written in Rust."
repository = "https://github.com/gotneb/rlox"

[dependencies]
